# Generated by Django 5.1.4 on 2025-01-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvecCarlingage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avec_carlingage', models.CharField(max_length=75)),
            ],
            options={
                'db_table': '"projet"."avec_carlingage"',
            },
        ),
        migrations.CreateModel(
            name='AvecPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avec_plots', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': '"projet"."avec_plots"',
            },
        ),
        migrations.CreateModel(
            name='ConsolidatedObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=75)),
                ('source', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(max_length=75, null=True)),
                ('description', models.TextField(null=True)),
                ('trade', models.CharField(max_length=100, null=True)),
                ('function', models.CharField(max_length=50, null=True)),
                ('lot', models.CharField(max_length=50, null=True)),
                ('room', models.CharField(max_length=50, null=True)),
                ('code_client_ouvrage', models.CharField(max_length=75, null=True)),
                ('code_client_object', models.CharField(max_length=50, null=True)),
                ('code_fournisseur', models.CharField(max_length=50, null=True)),
                ('facteur_choc', models.CharField(max_length=4, null=True)),
                ('degre_choc', models.CharField(max_length=4, null=True)),
                ('avec_plots', models.CharField(max_length=4, null=True)),
                ('avec_carlingage', models.CharField(max_length=4)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_last_modified', models.DateTimeField(null=True)),
                ('archived_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': '"j35"."consolidated_objects"',
            },
        ),
        migrations.CreateModel(
            name='ConsolidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('sources_priorities', models.TextField(blank=True, null=True)),
                ('display_mode', models.CharField(choices=[('First', 'First'), ('All', 'All')], max_length=50)),
            ],
            options={
                'db_table': 'consolidation_rule',
            },
        ),
        migrations.CreateModel(
            name='DegreChoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degre_choc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"projet"."degre_choc"',
            },
        ),
        migrations.CreateModel(
            name='FacteurChoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facteur_choc', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': '"projet"."facteur_choc"',
            },
        ),
        migrations.CreateModel(
            name='ObjectsFromCao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=75)),
                ('source', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(max_length=75, null=True)),
                ('description', models.TextField(null=True)),
                ('trade', models.CharField(max_length=100, null=True)),
                ('function', models.CharField(max_length=50, null=True)),
                ('lot', models.CharField(max_length=50, null=True)),
                ('room', models.CharField(max_length=50, null=True)),
                ('code_client_ouvrage', models.CharField(max_length=75, null=True)),
                ('code_client_object', models.CharField(max_length=50, null=True)),
                ('code_fournisseur', models.CharField(max_length=50, null=True)),
                ('facteur_choc', models.CharField(max_length=4, null=True)),
                ('degre_choc', models.CharField(max_length=4, null=True)),
                ('avec_plots', models.CharField(max_length=4, null=True)),
                ('avec_carlingage', models.CharField(max_length=4, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(null=True)),
                ('archived_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': '"j35"."objects_from_cao"',
            },
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouvrage', models.CharField(max_length=25, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('code_client', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ouvrage',
            },
        ),
        migrations.CreateModel(
            name='OwnerCodeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objconso_id', models.IntegerField()),
                ('fieldorder', models.IntegerField(unique=True)),
                ('fieldvalue', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"j35"."owner_code_details"',
            },
        ),
        migrations.CreateModel(
            name='OwnerCodeProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieledorder', models.IntegerField(unique=True)),
                ('fieldtype', models.IntegerField()),
                ('fieldvalue', models.CharField(max_length=50)),
                ('fieldlabel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"j35"."owner_code_properties"',
            },
        ),
        migrations.CreateModel(
            name='ProprieteDc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=50)),
                ('sourcespriorities', models.CharField(max_length=250)),
                ('displaymode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"projet"."proriete_dc"',
            },
        ),
    ]
